#!/bin/bash -e
if [ ! -e /data/naturalearth/110m_physical/110m_physical.zip ]; then
    mkdir -p /data/naturalearth/110m_physical
    curl -L https://naciscdn.org/naturalearth/110m/physical/110m_physical.zip -o /data/naturalearth/110m_physical/110m_physical.zip
    unzip -o /data/naturalearth/110m_physical/110m_physical.zip -d /data/naturalearth/110m_physical
fi
if [ ! -e /data/naturalearth/110m_cultural/110m_cultural.zip ]; then
    mkdir -p /data/naturalearth/110m_cultural
    curl -L https://naciscdn.org/naturalearth/110m/cultural/110m_cultural.zip -o /data/naturalearth/110m_cultural/110m_cultural.zip
    unzip -o /data/naturalearth/110m_cultural/110m_cultural.zip -d /data/naturalearth/110m_cultural
fi
if [ ! -e /data/naturalearth/50m_physical/50m_physical.zip ]; then
    mkdir -p /data/naturalearth/50m_physical
    curl -L https://naciscdn.org/naturalearth/50m/physical/50m_physical.zip -o /data/naturalearth/50m_physical/50m_physical.zip
    unzip -o /data/naturalearth/50m_physical/50m_physical.zip -d /data/naturalearth/50m_physical
fi
if [ ! -e /data/naturalearth/50m_cultural/50m_cultural.zip ]; then
    mkdir -p /data/naturalearth/50m_cultural
    curl -L https://naciscdn.org/naturalearth/50m/cultural/50m_cultural.zip -o /data/naturalearth/50m_cultural/50m_cultural.zip
    unzip -o /data/naturalearth/50m_cultural/50m_cultural.zip -d /data/naturalearth/50m_cultural
fi
if [ ! -e /data/naturalearth/10m_physical/10m_physical.zip ]; then
    mkdir -p /data/naturalearth/10m_physical
    curl -L https://naciscdn.org/naturalearth/10m/physical/10m_physical.zip -o /data/naturalearth/10m_physical/10m_physical.zip
    unzip -o /data/naturalearth/10m_physical/10m_physical.zip -d /data/naturalearth/10m_physical
fi
if [ ! -e /data/naturalearth/10m_cultural/10m_cultural.zip ]; then
    mkdir -p /data/naturalearth/10m_cultural
    curl -L https://naciscdn.org/naturalearth/10m/cultural/10m_cultural.zip -o /data/naturalearth/10m_cultural/10m_cultural.zip
    unzip -o /data/naturalearth/10m_cultural/10m_cultural.zip -d /data/naturalearth/10m_cultural
    mv /data/naturalearth/10m_cultural/10m_cultural/* /data/naturalearth/10m_cultural/.
fi
if [ ! -e /data/naturalearth/10m_physical/ne_10m_bathymetry_all.zip ]; then
    mkdir -p /data/naturalearth/10m_physical
    curl -L https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_bathymetry_all.zip -o /data/naturalearth/10m_physical/ne_10m_bathymetry_all.zip
    unzip -o /data/naturalearth/10m_physical/ne_10m_bathymetry_all.zip -d /data/naturalearth/10m_physical
fi

cp /data/shp2geojson.yaml /app
python3 /app/shp2geojson.py
GEOJSON_HASH=$(md5sum oceanus.json | awk '{print $1}')

tippecanoe \
  -P -z7 \
  -f \
  --low-detail=10 \
  --feature-filter-file=oceanus_filter.json \
  --coalesce --reorder \
  --coalesce-densest-as-needed --coalesce-smallest-as-needed \
  --detect-shared-borders \
  --simplify-only-low-zooms \
  --maximum-tile-bytes=400000 \
  -n oceanus \
  -o ./oceanus.mbtiles \
  ./oceanus.json

sqlite3 oceanus.mbtiles \
  "update metadata set value = '2.0.0+${GEOJSON_HASH}' where name = 'version'" \
  "delete from metadata where name in ('generator', 'generator_options')"